# Generated by Django 4.2 on 2024-08-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_producto_descripcion_alter_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='detalle',
            field=models.TextField(blank=True),
        ),
    ]
