# Generated by Django 4.2 on 2024-08-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_compra_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
