# Generated by Django 4.2 on 2024-08-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_compra_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='producto',
        ),
        migrations.AddField(
            model_name='compra',
            name='productos',
            field=models.ManyToManyField(to='menu.producto'),
        ),
    ]
